### ISSUE TITLE
Masking bugs in the collate function.

### ISSUE THREAD

**Issue by Carlosml26** [KHAKhazeus/BiBL#1]
Hi!

First of all, congrats on your paper being accepted in Coling. I would like to ask you about some parts of the code that I do not understand. They are related to the tokenizer.py specifically in the batch_encode_mask method. This method is going to prepare the batch masking part of the input sentence and graph, however right now it masking anything. 

First, the _mask_collate_padded_  variable (that is the one used as _input_ids_ of the batch) is created using _fil_collate_ids_ instead of_mask_fil_collate_ids_ which is the one that contains the masked inputs. :

```
for index, collate in enumerate(collate_ids):
    if len(collate) <= max_lm_len:
        maxlen = max((len(collate)), maxlen)
        fil_collate_ids.append(collate_ids[index])
        fil_rev_collate_ids.append(rev_collate_ids[index])
        mask_fil_sents_ids.append(mask_sents_ids[index])
        mask_fil_graph_ids.append(mask_graph_ids[index])
        mask_fil_collate_ids.append(mask_collate_ids[index])
        mask_fil_rev_collate_ids.append(mask_rev_collate_ids[index])
collate_padded = [x + [self.pad_token_id] * (maxlen - len(x)) for x in fil_collate_ids]
rev_collate_padded = [x + [self.pad_token_id] * (maxlen - len(x)) for x in fil_rev_collate_ids]
mask_collate_padded = [x + [self.pad_token_id] * (maxlen - len(x)) for x in fil_collate_ids]
mask_rev_collate_padded = [x + [self.pad_token_id] * (maxlen - len(x)) for x in fil_rev_collate_ids]
```

Therefore, right now the model is training without masking anything in the input. The second issue is related to the masking of the sentences in the same method since there isn't any masking strategy (there is just masking for the graphs). In the code, the variable _padded_mask_x_ is created in the same way as _padded_x_, without masking:

```
padded_x, _ = self.batch_encode_sentences(sentences, device=device)
# batch = super().batch_encode_plus(sentences, return_tensors='pt', pad_to_max_length=True)
for index, sent in enumerate(sentences):
    words = sent.split(" ")
    mask_num = math.floor(amr_ratio * len(words))
    rand_ind = random.sample(range(0, len(words)), mask_num)
    for ind in rand_ind:
        words[ind] = "<mask>"
    sentences[index] = " ".join(words)
padded_mask_x, _ = self.batch_encode_sentences(sentences, device=device)
```

This second issue is because of in the paper is explicitly define that the sentence is also masked. 

Best, 

Carlos

**Comment by KHAKhazeus** [comment]
Thanks for your kind reminder. After checking the code version, this part of the code was corrected afterward. I will correct this part manually in this repository and release a newer version with trained checkpoints ASAP.

**Comment by jalixdesign** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
kogn, @sxrdashuaige, @fakeorf3ke, @tenddo-RQ3PC, @cxlttt, @Akegarasu, @skyee1, @Fenghaibo-git, @Ga0Bo, @lake518j, @yang806, @david03kimo, @yungkit, @karencceeee, @zhangcy0203, @MikeyHe570, @iewaij, @tmors, @harelhuang, @ssmmtt, @wendykao, @wendyshusband, @gbques2827, @Jupnnn, @upkid, @Evansy, @GUI-nephelo, @btiger, @reki-cool, @seekerzz, @jhy616415267, @BIGheadLL, @Jasonjiang27, @alexwangx, @tofuntools, @zhongjingyun, @oujieww, @zorozilong, @Zcodeoooo, @george-yb, @ytzhang, @cmxnono, @EmmmaG, @huwence, @eric2016mark, @iftaken, @OstrichOnFire, @WORFEW, @ernie55ernie, @darklingpeggys20111564, @john523, @kimi471, @QiaoKe201512, @Times125, @lizhaoshan, @Xiang-cd, @yuanhu94, @qiaohaoforever, @HuangCongQing, @fancyChuan, @unknown0708, @PsiACE, @maobole, @we1l1n, @pangxie1987, @zhushuangquan001, @WsDorothy123, @wwtenator, @torg12323, @leeinwx, @1156721874, @wenruo95, @gechong, @zhaojinzhou, @Wang-yaole, @idashuishen, @todd-tao, @winterwd, @zcker, @JiweiMaster, @ldy1691github, @tyzero, @HuntFeng, @wangziwen98, @wrongerror, @bit-mon, @pfas, @muzhichu, @SoulAttacker, @ai-gamer, @Quietly-20201113, @INDNextHenry, @pengfengyong, @peniridis, @cxlttt, @lukejet, @zachgenius, @imspzero, @xingray1997
